### ISSUE TITLE
Cannot add a new project. Released UnityLauncherPro.exe is a buggy one?

### ISSUE THREAD

**Issue by zwcloud** [unitycoder/UnityLauncherPro#10]
![image](https://user-images.githubusercontent.com/6965758/79628403-48c03680-8173-11ea-9c2f-ecac919dce81.png)

After clicking the **Add Project** button, a file saving dialog popped up. It seems trying to save a file named "Project.Folder". And I cannot choose a `Assets` directory or its parent folder as the target. Clicking `Save` did nothing.

Using `UnityLauncherPro.exe`  inside [latest release](https://github.com/unitycoder/UnityLauncherPro/releases/tag/1.0.20)

**Comment by unitycoder** [comment]
Fixed in latest build now, also it was missing some code the read project name and other properties.

Should select the project root folder (not inside Assets/)

*reason to use filedialog with that "project.folder" dummy,
is that the default folder dialog is so horrible (and would prefer not include Ookii dialogs reference..)
![image](https://user-images.githubusercontent.com/5438317/79793496-58996f80-8359-11ea-9c85-6e33078204e8.png)
