### ISSUE TITLE
[Bug] Adding a project manually is seen as invalid?

### ISSUE THREAD

**Issue by ReDarkTechnology** [unitycoder/UnityLauncherPro#125]
I was trying to open a project and change it's platform but somehow the app doesn't detect it as a valid project because (maybe) the path somehow uses \ instead of /
![image](https://user-images.githubusercontent.com/53262904/221384042-a3c23da7-ca4f-469c-b32c-fc11eaf402a6.png)

I'm not sure if this is intentional or not, but I can't seem to be able to change the platform, unlike other projects
![image](https://user-images.githubusercontent.com/53262904/221384087-5cf563fb-5228-463e-98d0-10839a56c832.png)

**Comment by unitycoder** [comment]
yes, i think that was coming from the current way of just adding it in top of the list "as is".. (un-opened project)
but seems like the coming sorting updates force it auto-sorted,
so need to look into how to update/detect that row properly.

- [ ] validate project data/make it proper project in the list (so that it doesn't show path as red)
- [ ] when adding new project, make that row selected, to easily find it (since autosort forces it down the list, if sorted by date)
