### ISSUE TITLE
add link to release notes comparison tool

### ISSUE THREAD

**Issue by unitycoder** [unitycoder/UnityLauncherPro#135]
could be context menu or another button next to view release notes?
https://alpha.release-notes.ds.unity3d.com/search?fromVersion=2023.1.16f1&toVersion=2023.1.17f1

or somehow compare your installed version to latest or next published version..
(although you can set compared version easily on that website too)

**Comment by SixParQuatre** [comment]
Actually, it'd be cool to even use that page for the 'Release Notes' button; they are a lot easier to parse compared to the normal one.

**Comment by SixParQuatre** [comment]
So I wanted to do a fork and a pull request for this but for some reason I can't push anything on the new repo; so here's an implementation of the improvement as a patch based on the latest master.... I had to zip the .diff because the site won't let me upload that type of file. :eyeroll:
Here's the commit message associated with the change:

- Add option in settings/general to use alpha release note sites and use it in Tools.OpenReleaseNotes. As 6000 version changelog don't appear on the alpha site always use GetUnityReleaseNotes in that case.
- When using the alpha sites, we use it in comparison mode with the closest previous installed version. if none is found, use the same version as queried
- Added an extra parameter in Tools.FindNearestVersion to find the nearest below rather than above. Default value is false to maintain existing behaviour in existing calls.

Cheers!

[AlphaNotes.zip](https://github.com/unitycoder/UnityLauncherPro/files/15005750/AlphaNotes.zip)

**Comment by unitycoder** [comment]
@SixParQuatre  thanks! i'll have a look at it later.

**Comment by unitycoder** [comment]
this is now live!, thanks

**Comment by SixParQuatre** [comment]
Pleasure to help!
